# Generated by Django 5.1.7 on 2025-03-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_member_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
